//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUOI_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUOI_HOC()
        {
            this.THOI_KHOA_BIEU = new HashSet<THOI_KHOA_BIEU>();
        }
    
        public int BH_MABH { get; set; }
        public string BH_TENBH { get; set; }
        public string BH_GIOHOC { get; set; }
        public string BH_GIOTAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOI_KHOA_BIEU> THOI_KHOA_BIEU { get; set; }
    }
}
