//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAO_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAO_VIEN()
        {
            this.LOPs = new HashSet<LOP>();
        }
    
        public int GV_MAGV { get; set; }
        public int NND_MANHOM { get; set; }
        public string GV_HOTEN { get; set; }
        public string GV_CCCD { get; set; }
        public bool GV_GIOITINH { get; set; }
        public Nullable<System.DateTime> GV_NGAYSINH { get; set; }
        public string GV_DIACHI { get; set; }
        public string GV_SDT { get; set; }
        public string GV_EMAIL { get; set; }
        public string GV_MATKHAU { get; set; }
        public Nullable<int> GV_TRINHDOTA { get; set; }
    
        public virtual NHOM_NGUOI_DUNG NHOM_NGUOI_DUNG { get; set; }
        public virtual TRINH_DO TRINH_DO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
    }
}
