//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Web.Mvc;

    public partial class GIAO_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAO_VIEN()
        {
            this.LOPs = new HashSet<LOP>();
        }
    
        public int GV_MAGV { get; set; }
        public int NND_MANHOM { get; set; }

        [Required(ErrorMessage = "Họ tên giáo viên không được để trống")]
        public string GV_HOTEN { get; set; }

        [Required(ErrorMessage = "Căn cước công dân không được để trống")]
        [RegularExpression(@"^[0-9]{1,15}$", ErrorMessage = "Căn cước phải là số và tối đa 15 số")]
        public string GV_CCCD { get; set; }
        public bool GV_GIOITINH { get; set; }

        //[Required(ErrorMessage = "Vui lòng chọn ngày sinh")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> GV_NGAYSINH { get; set; }

        //[Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string GV_DIACHI { get; set; }

        [Required(ErrorMessage = "Chưa nhập số điện thoại")]
        [RegularExpression(@"^[0-9]{1,15}$", ErrorMessage = "Số điện thoại phải là số và không vượt quá 15 số")]
        public string GV_SDT { get; set; }

        //[Remote("IsEmailExist", "Teacher", ErrorMessage = "Email da ton tai")]
        [Required(ErrorMessage = "Email không được để trống")]
        [EmailAddress(ErrorMessage = "Không đúng định dạng email")]
        public string GV_EMAIL { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        public string GV_MATKHAU { get; set; }

        [Required(ErrorMessage = "Trình độ tiếng anh không được để trống")]
        public string GV_TRINHDOTA { get; set; }
    
        public virtual NHOM_NGUOI_DUNG NHOM_NGUOI_DUNG { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
    }
}
