//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAI_LOP()
        {
            this.LOPs = new HashSet<LOP>();
        }
    
        public int LL_MALOAI { get; set; }
        public string LL_TENLOAILOP { get; set; }
        public int TD_MATD { get; set; }
    
        public virtual TRINH_DO TRINH_DO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
    }
}
