//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.NGAY_DANG_KY = new HashSet<NGAY_DANG_KY>();
            this.THOI_KHOA_BIEU = new HashSet<THOI_KHOA_BIEU>();
        }
    
        public int L_MALOP { get; set; }
        public int LL_MALOAI { get; set; }
        public int GV_MAGV { get; set; }
        public string L_TENLOP { get; set; }
        public Nullable<byte> L_SISO { get; set; }
        public System.DateTime L_NGAYBD { get; set; }
        public System.DateTime L_NGAYKT { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual LOAI_LOP LOAI_LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGAY_DANG_KY> NGAY_DANG_KY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOI_KHOA_BIEU> THOI_KHOA_BIEU { get; set; }
    }
}
