//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTTAVEntities : DbContext
    {
        public QLTTAVEntities()
            : base("name=QLTTAVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUOI_HOC> BUOI_HOC { get; set; }
        public virtual DbSet<GIAO_VIEN> GIAO_VIEN { get; set; }
        public virtual DbSet<HOC_VIEN> HOC_VIEN { get; set; }
        public virtual DbSet<HOCKY_NAMHOC> HOCKY_NAMHOC { get; set; }
        public virtual DbSet<LOAI_LOP> LOAI_LOP { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<NGAY_DANG_KY> NGAY_DANG_KY { get; set; }
        public virtual DbSet<NHOM_NGUOI_DUNG> NHOM_NGUOI_DUNG { get; set; }
        public virtual DbSet<PHONG_HOC> PHONG_HOC { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THOI_KHOA_BIEU> THOI_KHOA_BIEU { get; set; }
        public virtual DbSet<TRINH_DO> TRINH_DO { get; set; }
    }
}
