//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGAY_DANG_KY
    {
        public int HV_MAHV { get; set; }
        public int L_MALOP { get; set; }
        public Nullable<System.DateTime> NDK_NGAYDK { get; set; }
        public Nullable<bool> NDK_CODK { get; set; }
    
        public virtual HOC_VIEN HOC_VIEN { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
