//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHOM_NGUOI_DUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOM_NGUOI_DUNG()
        {
            this.GIAO_VIEN = new HashSet<GIAO_VIEN>();
        }
    
        public int NND_MANHOM { get; set; }
        [Required(ErrorMessage = "Tên nhóm người dùng không được để trống")]
        [StringLength(50, ErrorMessage ="Tên nhóm người dùng không vượt quá 50 ký tự")]
        public string NND_TENNHOMND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAO_VIEN> GIAO_VIEN { get; set; }
    }
}
