//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOI_KHOA_BIEU
    {
        public int TKB_MATKB { get; set; }
        public int BH_MABH { get; set; }
        public int L_MALOP { get; set; }
        public int HKNH_MAHKNH { get; set; }
        public int PH_MAPHONG { get; set; }
        public string TKB_THUTRONGTUAN { get; set; }
        public string TKB_GHICHU { get; set; }
    
        public virtual BUOI_HOC BUOI_HOC { get; set; }
        public virtual HOCKY_NAMHOC HOCKY_NAMHOC { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual PHONG_HOC PHONG_HOC { get; set; }
    }
}
